server:
  port: 8081

#开启refresh接口
#这里需要注意,2.0之后，默认只开启了端点info、health。其他的需要通过management.endpoints.web.exposure.include进行额外配置。
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: refresh