server:
  port: 5000

spring:
  application:
    name: gateway-zuul
  zipkin:
    # 指定zipkin server的地址
    base-url: http://localhost:9411

  sleuth:
    sampler:
      # 指定需采样的请求的百分比，默认是0.1（即10%），这里方便查看设为90%（实际环境不要这样设置）
      probability: 0.9

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
  healthcheck:
    enabled: true # 启用健康检查,注意:需要引用spring boot actuator

management:
  security:
    enabled: false # 默认为true，改为false以便可以看到routes

zuul:
  prefix: /api # 路由前缀
  #ignored-services: * # 忽略所有微服务
  #ignored-services: movie-service # 忽略指定服务
  #sensitive-headers: Cookie,Set-Cookie,Authorization # 指定全局敏感header，默认是Cooki,Set-Cookie,Authorization
  routes:
    user-service: /user/**
    movie-service: /movie/**
  #    # 这里可以自定义
  #    demo1:
  #      # 匹配的路由规则
  #      path: /user/**
  #      # 路由的目标服务名
  #      serviceId: user-service
  #    demo2:
  #      # 匹配的路由规则
  #      path: /movie/**
  #      # 路由的目标服务名
  #      serviceId: movie-service

  # 禁用指定过滤器设置
  #PreRequestLogFilter:
  #  pre:
  #    disable: true # 禁用我们创建的PreRequestLogFilter过滤器

  # 配置限流
  ratelimit:
    enabled: true
    # 对应存储类型(用来统计存储统计信息)
    repository: redis
    policy-list:
      user-service:
        # 每秒允许多少个请求
        - limit: 2
          # 刷新时间(单位秒)
          refresh-interval: 1
          # 根据什么统计
          type:
            - url

# swagger开启开关
swagger:
  enabled: true
# 下面的设置针对超大文件上传（比如500M），提升了超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 60000

ribbon:
  ConnectionTimeout: 3000
  ReadTimeout: 60000
