server:
  port: 8001

management:
  endpoint:
    health:
      show-details: always

#通过spring.application.name属性，我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问。
spring:
  application:
    name: user-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    username: sa
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  logging:
    level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health  #检测实例健康
        health-check-interval: 10s   #每隔10s检查
        #        hostname: 127.0.0.1    ##配置实例地址
        register: true  #自动注册
        service-name: ${spring.application.name} #实例名称
      host: 127.0.0.1 #consul地址
      port: 8500  #consul端口
#      config:
#        enabled: true  #是否开启配置中心
#        format: yaml   #配置中心解析样式

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@