server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: sampleservice-config-server
  cloud:
    config:
      server:
        git:
          # 配置Git仓库地址
          uri: https://github.com/hanyunpeng0521/spring-cloud-learn.config
          default-label: master
          refresh-rate: 10
    #              # Git仓库账号（如果需要认证）
#          username: m13839441583@163.com
#              # Git仓库密码（如果需要认证）
#          password: hyp212655
    bus:
      trace:
        enabled: true # 开启cloud bus跟踪
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: my_vhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
